export const BLOG_UPDATE_REQUEST = "BLOG_UPDATE_REQUEST";
export const BLOG_UPDATE_SUCCESS = "BLOG_UPDATE_SUCCESS";
export const BLOG_UPDATE_FAIL = "BLOG_UPDATE_FAIL";

export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";

export const POST_REVIEW_DELETE_REQUEST = "POST_REVIEW_DELETE_REQUEST";
export const POST_REVIEW_DELETE_SUCCESS = "POST_REVIEW_DELETE_SUCCESS";
export const POST_REVIEW_DELETE_FAIL = "POST_REVIEW_DELETE_FAIL";

export const POST_REVIEW_CREATE_REQUEST = "POST_REVIEW_CREATE_REQUEST";
export const POST_REVIEW_CREATE_SUCCESS = "POST_REVIEW_CREATE_SUCCESS";
export const POST_REVIEW_CREATE_FAIL = "POST_REVIEW_CREATE_FAIL";
export const POST_DETAILS_CHANGE = "POST_DETAILS_CHANGE";
export const POST_REVIEW_CHANGE = " POST_REVIEW_CHANGE ";
export const POST_REVIEWREMOVE_CHANGE = " POST_REVIEWREMOVE_CHANGE ";

export const POST_LIKE_REQUEST = " POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = " POST_LIKE_SUCCESS";
export const POST_LIKE_FAIL = " POST_LIKE_FAIL";
export const POST_LIKE_RESET = " POST_LIKE_RESET";

export const POST_UNLIKE_REQUEST = " POST_UNLIKE_REQUEST";
export const POST_UNLIKE_SUCCESS = " POST_UNLIKE_SUCCESS";
export const POST_UNLIKE_FAIL = " POST_UNLIKE_FAIL";
export const POST_UNLIKE_RESET = " POST_UNLIKE_RESET";
